name: Deploy Infrastructure

on:
  push:
    branches:
      - mains
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  #  Change to your AWS region   

      - name: Verify AWS Identity
        run: aws sts get-caller-identity
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform
        
      - name: Terraform Apply
        run: terraform destroy -auto-approve
        working-directory: terraform

  dynamic-inventory:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install boto3

      - name: Generate Dynamic Inventory
        run: |
          python dynamic_inventory.py > inventory.json
        env:
          AWS_REGION: eu-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ansible
        
      - name: Upload Inventory as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ansible-inventory
          path: ansible/inventory.json

  ansible:
    needs: dynamic-inventory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Inventory
        uses: actions/download-artifact@v4
        with:
          name: ansible-inventory
          path: ansible
        
      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh  #  Ensure the .ssh directory exists
          chmod 700 ~/.ssh
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        
      - name: Disable SSH Host Key Checking
        run: |
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          echo "UserKnownHostsFile=/dev/null" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Set SSH Public Key as an Environment Variable
        run: echo "SSH_PUBLIC_KEY=${{ secrets.SSH_PUBLIC_KEY }}" >> $GITHUB_ENV

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.json ansible/ansible_playbook.yml

  # inspec:
  #   needs: ansible
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Download Inventory
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: ansible-inventory
  #         path: ansible

  #     - name: Install InSpec
  #       run: |
  #         curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec

  #     - name: Accept InSpec License
  #       run: echo "CHEF_LICENSE=accept-no-persist" >> $GITHUB_ENV

  #     - name: Run InSpec Tests
  #       run: |
  #         export TARGET_HOST=$(jq -r '.all.hosts[0]' ansible/inventory.json)
  #         inspec exec inspec-profile --controls=devops_challenge.rb -t ssh://devops@$TARGET_HOST --key-files ~/.ssh/id_rsa
