name: Deploy Infrastructure

on:
  push:
    branches:
      - mains

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  # Change to your AWS region   

      - name: Verify AWS Identity
        run: aws sts get-caller-identity
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform
        
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Copy Private Key to Ansible Directory
        run: |
          cp terraform/private-key.pem ansible/private-key.pem
          chmod 600 ansible/private-key.pem  # Ensure correct permissions

      - name: Upload Private Key as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: private-key
          path: ansible/private-key.pem

  dynamic-inventory:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install boto3

      - name: Generate Dynamic Inventory
        run: |
          python dynamic_inventory.py > inventory.json
        env:
          AWS_REGION: eu-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ansible
        
      - name: Upload Inventory as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ansible-inventory
          path: ansible/inventory.json

  ansible:
    needs: dynamic-inventory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Inventory
        uses: actions/download-artifact@v4
        with:
          name: ansible-inventory
          path: ansible

      - name: Download Private Key
        uses: actions/download-artifact@v4
        with:
          name: private-key
          path: ansible

      - name: Set Correct Permissions for Private Key
        run: chmod 600 ansible/private-key.pem

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.json --private-key ansible/private-key.pem ansible/ansible_playbook.yml
